### ISSUE TITLE
Add OTA or distribution partner information (?)

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-booking-api#15]
**Is your feature request related to a problem? Please describe.**
It is important for a channel manager to know what partner (OTA a a distribution partner) is booking an inventory because ...?

**Describe the solution you'd like**
Add OTA or distribution partner name to booking request.

---

*This issue was split away from windingtree/wt-booking-api#14*

**Comment by czervenka** [comment]
@koushik-chatterjee is this what you proposed in windingtree/wt-booking-api#14? Could you please also briefly describe what is the OTA / distribution partner name used for?

**Comment by koushik-chatterjee** [comment]
Hi, OTA/Distribution partner name can be a channel name or a travel agent name or a tour operator name which we would need because hotels using WT platform would like to know what is the actual primary origin of the booking by the customer.So lets say we have OTA1 and OTA2 both of them uses WT API to read property details and initiate a booking by sending the booking API request to us.So that means we can get booking request from both the partners OTA1 or OTA2 using WT API platform. So when we confirm the booking and deliver to hotels we would also need to notify them from which OTA the booking has come from, OTA1 or OTA2 which is primary source of booking creation.Otherwise all the time we have to consider the booking request came from WT without any differentiator what is the primary origin.Let me know if you need further clarification or use case for this.

**Comment by czervenka** [comment]
This is perfect, thank you @koushik-chatterjee.

**Comment by czervenka** [comment]
We agreed on a simple text property in booking request for partner name for now. 

I also added https://github.com/windingtree/wt-booking-api/issues/16 for full solution.
